version: 2

models:
  - name: test_table
    description: One record per customer aggregating number of orders
    columns:
      - name: first_name
        description: Customer first name
        data_tests:
          - not_null
      - name: last_name
        description: Customer last name
        data_tests:
          - not_null
      - name: customer_id
        description: Customer unique id
        data_tests:
          - unique
          - not_null
      - name: orders_count
        description: Count of total orders
        data_tests:
          - not_null